server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: ${APP_NAME:FIAP Lanches}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:fiaplanches}?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
apipag: https://pagamento.free.beeceptor.com/pag