server:
  port: 8080
spring:
  application:
    name: FIAP Lanches
  datasource:
    url: jdbc:mysql://localhost:3306/fiaplanches?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update